### ISSUE TITLE
Fix HTTP/HTTPS

### ISSUE THREAD

**Issue by cristiano-clemente** [GCE-NEIIST/GCE-NEIIST-webapp#261]
http://gce-neiist.org is working but I get a "Not Secure" message (Chrome 84 on Windows 10).
https://gce-neiist.org is not working.

**Comment by facasaca** [comment]
Just found out this is due to mixed content:
https://support.google.com/blogger/answer/6286127?hl=en

![Mixed Content](https://user-images.githubusercontent.com/43506001/98019114-482e7b00-1df9-11eb-82cc-632f397d882c.png)

**Comment by facasaca** [comment]
It also only happens on the landing page.
