### ISSUE TITLE
GCE-Thesis: UI and UX improvements

### ISSUE THREAD

**Issue by RafaelAPB** [GCE-NEIIST/GCE-NEIIST-webapp#37]
~~-Re-add the explanation about the service (it's commented). Make it a little simpler, if possible.~~

-Show, bellow the search bar, the total number of theses. when the user clicks on the area(s), update a label below the search bar with the number of theses returned by the filter.

-If no answers are returned (like selecting a thesis in "CS" and "G" areas), write a message stating that there are no results.  Add a container, since it is strange to see the footer above the search options. Same problem if you choose "SE" and "G".

~~-When a user clicks a thesis, make a call to the backend: /thesis//incrementClick/:id
where ``id`` is the thesis ID. This way we can track theses' popularity.~~

**Comment by jptrindade** [comment]
4007255be36aa62c138433b0f6a5dedc1d6edc95 
ea4a7b795c9cfec1e0fd5cf002dbd343ce7786cf
